apiVersion: v1              # POD's Volume used by its containers
kind: Pod
metadata:
  name: busyboxab
  namespace: default
spec:
  containers:
  - image: busybox
  name: busy1
  command:
  - sleep 
  - "3600"
  volumeMounts:
  - mountPath: /somedir
    name: my-volume
  volumes:
  - name: my-volume
    emptyDir: {}
