apiVersion: v1
kind: Pod
metadata:
  name: busybox3
spec:
  containers:
  - image: busybox
    name: busy
    command:              # takes command to run , passed as list # also possible command: ["", "", ] format
      - sleep
      - "3600"
