apiVersion: v1
kind: Pod
metadata:
  name: test1
spec:
  containers:
  - name: test1
    image: cirros
    command: ["/bin/sh", "-c", "env"]             # container will run with this command when started 
    envFrom:
      - configMapRef:                             # test1 POD refers to ConfigMap for a ENV Variable named 'variable'
          name: variables
