apiVersion: batch/v1beta1
kind: CronJob
metadata: 
  name: hello
spec:
  schedule: "*/1 * * * *"         # When to do the task
  jobTemplate:
    spec:
      template:                   # POD Template
        spec:
          containers:
          - name: hello
            image: busybox
            args:                 # task
            - /bin/sh
            - -c
            - date; echo hello from the K8s cluster
          restartPolicy: OnFailure
