apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - name: busybox                     #Container1 : busybox
    image: busybox
    command:
      - sleep
      - "3600" 
  - name: nginx                       #Container2 : nginx
    image: nginx
