apiVersion: v1
kind: Pod
metadata:
  name: nginx-probes
  labels:
    role: web
spec:
  containers:
  - name: nginx-probes
    image: nginx
    readinessProbe:                           # probe readinessProbe defined for POD's container
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:                            # probe livenessProbe defined for POD's container
      tcpSocket:
        port: 80
      initialDelaySeconds: 20
      periodSeconds: 20

