apiVersion: apps/v1
kind: ReplicaSet              # RS creates replica of Pods # Assume Deployment is not created ! try out 
metadata:
  name: rsdemo
spec:
  replicas: 2
  selector:
    matchLabels:              # matchLabels this keyword is needed for RS 
      app: myapp
  template:                   # pod template 
    metadata:
      name: nginxrs           # pod name ?
      labels:
        app: myapp            # pod label
    spec:
      containers:             # pod's container
      - name: nginx
        image: nginx
