apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:               # Pod selector
    app: MyApp
  ports:
    - protocol: TCP
      port: 80            # port Cluster exposes | port anyone in the cluster accesses
      targetPort: 9376    # port POD listens to | port container exposes
