apiVersion: v1
kind: Service
metadata:
  name: mywebserver
spec:
  selector:                 # mention a label in selector to identify PODs
    run: nginx
  ports:
  - port: 80
    name: whatever
  type: NodePort            # type of service NodePort
