apiVersion: batch/v1
kind: Job
metadata:
  name: simple-job
spec:
  template:                 # POD template
    spec:
      containers:
      - name: sleepy
        image: alpine
        command: [ "/bin/sleep" ]
        args: [ "5" ]
      restartPolicy: Never
